#!/bin/bash
# This wrapper script is used by git to verify signatures made using
# an expired key.
# https://bugs.torproject.org/19737
set -e
if [ $# -eq 4 ] && [ "$1" = '--status-fd=1' ] \
        && [ "$2" = '--verify' ]
then
    gpgv "$1" "$3" "$4" | sed 's/^\[GNUPG:\] EXPKEYSIG /\[GNUPG:\] GOODSIG /'
    exit ${PIPESTATUS[0]}
else
    exec gpg "$@"
fi
